feed/urls.py
from django.urls import path

from . import views

app_name = 'feed'

urlpatterns = [
    path("",views.HomePage.as_view(),name="index"),
    path("<int:pk>/",views.PostDetailView.as_view(),name="detail")
]

til/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from feed import urls as feed_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(feed_urls,namespace="feed")),
    path('',include("allauth.urls")),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length=240)
    date= models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    def __str__(self):
        return self.text[0:100]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile",
    )
    image  = ImageField(upload_to='profiles')
    def __str__(self):
        return self.user.username
    
@receiver (post_save,sender=User) 
def create_user_profile (sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

feed/views.py
from django.views.generic import ListView,DetailView
from .models import Post

class HomePage(ListView):
    http_method_names=["get"]
    template_name="feed/homepage.html"
    model = Post
    context_object_name = "posts"
    queryset= Post.objects.all().order_by('-id')[0:30]

class PostDetailView(DetailView):
    model = Post
    template_name = "feed/detail.html"
    model= Post
    context_object_name = "post"

profiles/views.py
from django.shortcuts import render

# Create your views here.

feed/templates/feed/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
    Details from {{post.text}}
{% endblock title %}
    

{% block body %}
    <!-- component -->
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style="width: 50rem;">
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{post.date|date:"F j, Y, g:i:a"}}</span>
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600"> {{post.text}} </p>
    </div>
    <div class="flex justify-between items-center mt-4">
        <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">Read more</a>
        <div>
            <a class="flex items-center" href="#">
                {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block"
                src="{{ im.url }}"
                alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
            </a>
        </div>
    </div>
</div>
{% endblock body %}
    

feed/templates/feed/homepage.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
homepage title
{% endblock title %}

{% block body %}
{% for post in posts%}


<!-- component -->
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style="width: 50rem;">
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{post.date|date:"F j, Y, g:i:a"}}</span>
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600"> {{post.text}} </p>
    </div>
    <div class="flex justify-between items-center mt-4">
        <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">Read more</a>
        <div>
            <a class="flex items-center" href="#">
                {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block"
                src="{{ im.url }}"
                alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
            </a>
        </div>
    </div>
</div>
<hr>
{% endfor %}
{% endblock body %}

til/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 
    {% block title %}
        Default title 
    {% endblock title %}
        </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
</head>
<body>
<div class="min-h-screen flex flex-row bg-gray-100">
  <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
    <div class="flex items-center justify-center h-20 shadow-md">
      <h1 class="text-3xl uppercase text-indigo-500">TIL</h1>
    </div>
    <ul class="flex flex-col py-4">
      <li>
        <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
          <span class="text-sm font-medium">Home</span>
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li>
            <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
            <span class="text-sm font-medium">Logout</span>
            </a>
        </li>
      {% else %}
        <li>
            <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
            <span class="text-sm font-medium">Login</span>
            </a>
        </li>
      {% endif %}
    </ul>
  </div>
  <div class="p-16">
    {% block body %}
        {% block content %}{% endblock %}
    {% endblock %}
  </div>
</div>
</body>
</html>